services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: backend
    container_name: spring-boot-app
    ports:
      - "8181:8181"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: frontend
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
