apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
        - name: spring-container
          image: seu-usuario/spring-backend:latest
          ports:
            - containerPort: 8181
          env:
            - name: REDIS_HOST
              value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: spring-backend
  ports:
    - port: 8181
      targetPort: 8181
  type: ClusterIP
